
#trigger:
#- main

pool:
  name: Terraform-Mwaa-Pool

variables:
  mwaa_environment_name: 'my-mwaa-env' 
  source_bucket_arn: 'arn:aws:s3:::sp-classifier-mwaa'  

stages:
- stage: deploy_stage
  displayName: terraform stage
  jobs:
 
  - job: deploy_job
    displayName: terraform job
    timeoutInMinutes: 240
    steps:

    - task: TerraformInstaller@1
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: 'latest'   

    - task: TerraformTaskV4@4
      inputs:
        provider: 'aws'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-aws-mwaa/examples/basic'
        backendServiceAWS: 'aws-us-east-1'
        backendAWSBucketName: 'azure-terraform-state-s3-bucket'
        backendAWSKey: 'terraform.tfstate'
    

    - task: TerraformTaskV4@4
      inputs:
        provider: 'aws'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-aws-mwaa/examples/basic'
        environmentServiceNameAWS: 'aws-us-east-1'
        environmentVariables:
        TF_VAR_mwaa_environment_name: 'my-mwaa-environment'  # Replace with your desired name
        TF_VAR_source_bucket_arn: 'arn:aws:s3:::sp-classifier-mwaa'  # Replace with your actual bucket ARN

      
#    - task: TerraformTaskV4@4
#      inputs:
#        provider: 'aws'
#        command: 'apply'
#        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-aws-mwaa/examples/basic'
#        environmentServiceNameAWS: 'aws-us-east-1'

 
#    - task: Wait@1
#      inputs:
#        Value: '120'
#        Unit: 'minutes'
  
 
#    - task: TerraformTaskV4@4
#      inputs:
#        provider: 'aws'
#        command: 'destroy'
#        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-aws-mwaa/examples/basic'
#        environmentServiceNameAWS: 'aws-us-east-1'

# Schedule configuration added below
schedules:
- cron: "00 16 * * *" # "min hour day" 
  displayName: Run every day at 3:30 PM UTC
  branches:
    include:
    - main  # You can adjust the branch to target specific branches for execution
