
#trigger:
#- main

pool:
  vmImage: ubuntu-latest

steps:
    - task: TerraformTaskV4@4
      inputs:
        provider: 'aws'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-aws-mwaa/examples/basic'
        backendServiceAWS: 'aws-us-east-1'
        backendAWSBucketName: 'azure-terraform-state-s3-bucket'
        backendAWSKey: 'terraform.tfstate'
    

 
    - task: TerraformTaskV4@4
      inputs:
        provider: 'aws'
        command: 'destroy'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-aws-mwaa/examples/basic'
        environmentServiceNameAWS: 'aws-us-east-1'
