
trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: deploy_stage
  displayName: terraform stage
  jobs:
  - job: deploy_job
    displayName: terraform job
    steps:

    - task: TerraformInstaller@1
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: 'latest' 
    - task: TerraformTaskV4@4
      inputs:
        provider: 'aws'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-aws-mwaa/examples/basic'
        backendServiceAWS: 'aws-us-east-1'
        backendAWSBucketName: 'test-airflow-s3-bucket'
        backendAWSKey: 'tf/terraform.tfstate'
        
    - task: TerraformTaskV4@4
      inputs:
        provider: 'aws'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)terraform-aws-mwaa/examples/basic'
        environmentServiceNameAWS: 'aws-us-east-1'
        