

trigger:
- main

pool:
  name: Terraform-Mwaa-Pool

stages:
- stage: deploy_stage
  displayName: terraform stage
  jobs:
 
  
  - job: destroy_job
    displayName: Destroy Job
    steps:        
    - task: TerraformTaskV4@4
      inputs:
        provider: 'aws'
        command: 'destroy'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-aws-mwaa/examples/basic'
        environmentServiceNameAWS: 'aws-us-east-1'