

trigger:
- main

pool:
  name: Terraform-Mwaa-Pool

stages:
- stage: deploy_stage
  displayName: terraform stage
  jobs:
  - job: deploy_job
    displayName: terraform job
    steps:

    - task: TerraformInstaller@1
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: 'latest'   


    - task: PowerShell@2 
      displayName: 'Set working directory'
      inputs:
        targetType: inline
        script: |
          cd $(System.DefaultWorkingDirectory)/terraform-aws-mwaa/examples/basic
          Write-Host "Working directory is now: $(pwd)"
      
  
    - task: TerraformTaskV4@4
      inputs:
        provider: 'aws'
        command: 'init'
        backendServiceAWS: 'aws-us-east-1'
        backendAWSBucketName: 'azure-terraform-state-s3-bucket'
        backendAWSKey: 'terraform.tfstate'
    

    - task: TerraformTaskV4@4
      inputs:
        provider: 'aws'
        command: 'plan'
        environmentServiceNameAWS: 'aws-us-east-1'
 

      
    - task: TerraformTaskV4@4
      inputs:
        provider: 'aws'
        command: 'apply'
        environmentServiceNameAWS: 'aws-us-east-1'
    
    
    
    - task: TerraformTaskV4@4
      inputs:
        provider: 'aws'
        command: 'destroy'
        environmentServiceNameAWS: 'aws-us-east-1'