
trigger:
- main

pool:
  name: Terraform-Mwaa-Pool

stages:
- stage: deploy_stage
  displayName: terraform stage
  jobs:
  - job: deploy_job
    displayName: terraform job
    steps:

    - task: TerraformInstaller@1
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: 'latest' 
    - task: PowerShell@2 # Use PowerShell@2 if you have a Windows agent
      inputs:
        targetType: 'inline' 
        script: |
          # Assuming your VPC module structure is within a 'modules/vpc' directory
          TF_MODULE_PATH=".terraform/modules/vpc/main.tf"

          # Remove the 'enable_classiclink' line 
          sed -i '/enable_classiclink/d' $TF_MODULE_PATH

          # Remove the 'enable_classiclink_dns_support' line
          sed -i '/enable_classiclink_dns_support/d' $TF_MODULE_PATH     
    - task: TerraformTaskV4@4
      inputs:
        provider: 'aws'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-aws-mwaa/examples/basic'
        backendServiceAWS: 'aws-us-east-1'
        backendAWSBucketName: 'test-airflow-s3-bucket'
        backendAWSKey: 'tf/terraform.tfstate'
        commandOptions: '-upgrade'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'aws'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-aws-mwaa/examples/basic'
        environmentServiceNameAWS: 'aws-us-east-1'